import test from 'node:test';import assert from 'node:assert/strict';import {MidiRuntime} from '../web/midi-runtime.js';
const cc=(raw,number=74)=>({type:'cc',channel:1,number,raw,normalized:raw/127,gate:raw>0});
const absolute={id:'abs',source:{type:'cc',channel:1,number:74},target:{kind:'param',id:'cutoff'},mode:'absolute',pickup:true};
test('absolute parameter waits for pickup crossing',async()=>{let n=0;const sent=[];const runtime=new MidiRuntime({send:cmd=>{sent.push(cmd);return `c${++n}`;},describe:async()=>({normalized:.5,writable:true})});await runtime.activate([absolute]);assert.deepEqual(runtime.handle(cc(10)),[]);assert.deepEqual(runtime.handle(cc(50)),[]);assert.deepEqual(runtime.handle(cc(80)),['c1']);assert.equal(sent[0].action,'set_normalized');});
test('absolute movement remains one in flight with latest value',async()=>{let n=0;const sent=[];const runtime=new MidiRuntime({send:cmd=>{sent.push(cmd.args.value);return `c${++n}`;},describe:async()=>({normalized:0,writable:true})});await runtime.activate([{...absolute,pickup:false}]);runtime.handle(cc(10));runtime.handle(cc(20));runtime.handle(cc(100));assert.deepEqual(sent,[10/127]);assert.equal(runtime.settle({id:'c1',status:'ack',result:{param:{normalized:10/127}}}),'c2');assert.deepEqual(sent,[10/127,100/127]);});
test('relative param uses device delta semantics',async()=>{const sent=[];const runtime=new MidiRuntime({send:cmd=>{sent.push(cmd);return 'd1';},describe:async()=>null});await runtime.activate([{id:'rel',source:{type:'cc',channel:1,number:10},target:{kind:'param',id:'cutoff'},mode:'relative-twos'}]);runtime.handle(cc(127,10));assert.deepEqual(sent[0],{target:'param',action:'delta',args:{id:'cutoff',d:-1}});});
test('note gate mapping deduplicates repeated gate state',async()=>{let n=0;const sent=[];const runtime=new MidiRuntime({send:cmd=>{sent.push(cmd);return `k${++n}`;},describe:async()=>null});await runtime.activate([{id:'key',source:{type:'note',channel:1,number:60},target:{kind:'key',n:2}}]);const on={type:'note',channel:1,number:60,raw:100,normalized:.8,gate:true};const off={...on,gate:false,raw:0,normalized:0};runtime.handle(on);runtime.handle(on);runtime.handle(off);assert.deepEqual(sent.map(x=>x.args.z),[1,0]);});
test('script/device switch deactivates old mappings',async()=>{const sent=[];const runtime=new MidiRuntime({send:cmd=>{sent.push(cmd);return 'x';},describe:async()=>({normalized:0,writable:true})});await runtime.activate([{...absolute,pickup:false}]);runtime.deactivate();runtime.handle(cc(127));assert.equal(sent.length,0);});
test('uncertain settlement replays latest absolute target',async()=>{let n=0;const sent=[];const runtime=new MidiRuntime({send:cmd=>{sent.push(cmd.args.value);return `u${++n}`;},describe:async()=>({normalized:0,writable:true})});await runtime.activate([{...absolute,pickup:false}]);runtime.handle(cc(10));runtime.handle(cc(90));assert.equal(runtime.settle({id:'u1',status:'uncertain'}),'u2');assert.deepEqual(sent,[10/127,90/127]);});
test('failed descriptor activation leaves no partially active mappings',async()=>{const runtime=new MidiRuntime({send:()=> 'x',describe:async id=>{if(id==='bad')throw new Error('missing');return {normalized:0,writable:true};}});await assert.rejects(()=>runtime.activate([{...absolute,id:'good'},{...absolute,id:'bad',target:{kind:'param',id:'bad'}}]));assert.equal(runtime.mappings.length,0);assert.equal(runtime.states.size,0);});

test('explicit reject drops queued absolute retry',async()=>{let n=0;const sent=[];const runtime=new MidiRuntime({send:cmd=>{sent.push(cmd.args.value);return `r${++n}`;},describe:async()=>({normalized:0,writable:true})});await runtime.activate([{...absolute,pickup:false}]);runtime.handle(cc(10));runtime.handle(cc(90));assert.equal(runtime.settle({id:'r1',status:'reject',error:'invalid'}),null);assert.deepEqual(sent,[10/127]);});
