import test from 'node:test';import assert from 'node:assert/strict';
import {parseMidiMessage,sourceKey,relativeDelta,SoftTakeover,ProfileStore,validateMapping,deviceFingerprint} from '../web/midi-core.js';
import {midiAvailability,midiPorts,requestMidiAccess} from '../web/midi-access.js';
import {MidiRuntime} from '../web/midi-runtime.js';

test('parses CC note and pitch bend',()=>{assert.equal(parseMidiMessage([0xb2,74,127]).channel,3);assert.equal(parseMidiMessage([0x90,60,0]).gate,false);assert.equal(parseMidiMessage([0xe0,0,64]).raw,8192);});
test('source keys and fingerprints are stable',()=>{assert.equal(sourceKey({type:'cc',channel:2,number:7}),'cc:2:7');assert.match(deviceFingerprint({manufacturer:'M',name:'N',id:'I'}),/M.*N.*I/);});
test('relative modes decode common controller formats',()=>{const e={type:'cc',raw:127};assert.equal(relativeDelta(e,'relative-twos'),-1);assert.equal(relativeDelta({...e,raw:65},'relative-offset'),1);assert.equal(relativeDelta({...e,raw:65},'relative-sign'),-1);});
test('soft takeover waits for crossing',()=>{const p=new SoftTakeover(.01);p.arm(.5);assert.equal(p.accept(.1),false);assert.equal(p.accept(.6),true);});
function memoryStorage(){const mem=new Map();return{getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,v),mem};}
const validMap=()=>validateMapping({id:'x',source:{type:'cc',channel:1,number:1},target:{kind:'param',id:'cutoff'},mode:'absolute'});
test('profiles isolate exact script and device',()=>{const storage=memoryStorage();const s=new ProfileStore(storage);s.save('A','dev',[validMap()]);assert.equal(s.load('A','dev').length,1);assert.equal(s.load('B','dev').length,0);});
test('profile keys cannot target object prototypes',()=>{const storage=memoryStorage();const s=new ProfileStore(storage);s.save('__proto__','constructor',[validMap()]);assert.equal(s.load('__proto__','constructor').length,1);assert.equal({}.x,undefined);});
test('Web MIDI reports secure-context state and avoids sysex',async()=>{assert.equal(midiAvailability({},false).code,'insecure');let options;await requestMidiAccess({requestMIDIAccess:async value=>{options=value;return {};}});assert.deepEqual(options,{sysex:false,software:false});const ports=midiPorts({inputs:new Map([['i',{id:'i',name:'in'}]]),outputs:new Map([['o',{id:'o',name:'out'}]])});assert.equal(ports.inputs[0].name,'in');assert.equal(ports.outputs[0].name,'out');});
const mapping=(overrides={})=>({id:'m',source:{type:'cc',channel:1,number:10},target:{kind:'param',id:'cutoff'},mode:'absolute',pickup:true,...overrides});
test('absolute runtime applies pickup, backpressure and uncertain replay',async()=>{let n=0;const sent=[];const r=new MidiRuntime({describe:async()=>({normalized:.5,writable:true}),send:c=>{sent.push(c);return `c${++n}`;}});await r.activate([mapping()]);r.handle({type:'cc',channel:1,number:10,normalized:.1,raw:13});assert.equal(sent.length,0);r.handle({type:'cc',channel:1,number:10,normalized:.6,raw:76});r.handle({type:'cc',channel:1,number:10,normalized:.8,raw:102});assert.equal(sent.length,1);r.settle({id:'c1',status:'uncertain'});assert.equal(sent.length,2);assert.equal(sent[1].args.value,.8);});
test('explicit reject drops queued absolute retry',async()=>{let n=0;const sent=[];const r=new MidiRuntime({describe:async()=>({normalized:0,writable:true}),send:c=>{sent.push(c);return `c${++n}`;}});await r.activate([mapping({pickup:false})]);r.handle({type:'cc',channel:1,number:10,normalized:.2,raw:25});r.handle({type:'cc',channel:1,number:10,normalized:.9,raw:114});r.settle({id:'c1',status:'reject',error:'bad'});assert.equal(sent.length,1);});
test('relative param mapping sends delta',async()=>{const sent=[];const r=new MidiRuntime({describe:async()=>null,send:c=>{sent.push(c);return 'x';}});await r.activate([mapping({mode:'relative-twos',pickup:false})]);r.handle({type:'cc',channel:1,number:10,raw:127,normalized:1});assert.equal(sent[0].action,'delta');assert.equal(sent[0].args.d,-1);});
test('failed descriptor activation leaves no partial profile',async()=>{const r=new MidiRuntime({describe:async id=>id==='bad'?null:{normalized:0,writable:true},send:()=> 'x'});await assert.rejects(()=>r.activate([mapping(),mapping({id:'m2',target:{kind:'param',id:'bad'}})]));assert.equal(r.states.size,0);});
