import test from 'node:test';
import assert from 'node:assert/strict';
import {PROTOCOL_VERSION,ProtocolError,initialProtocolState,reduceProtocolState,resyncRequest,CommandTracker,OutboundQueue} from '../web/realtime-protocol.js';
const snapshot=(rev,state)=>({v:PROTOCOL_VERSION,type:'snapshot',rev,state});
const delta=(rev,operations)=>({v:PROTOCOL_VERSION,type:'delta',rev,operations});

test('snapshot establishes authoritative state and revision',()=>{const state=reduceProtocolState(initialProtocolState(),snapshot(7,{transport:{playing:true}}));assert.equal(state.status,'synced');assert.equal(state.revision,7);assert.equal(state.data.transport.playing,true);});
test('ordered delta applies immutable set and delete operations',()=>{const base=reduceProtocolState(initialProtocolState(),snapshot(2,{tracks:[{level:.5}],old:1}));const next=reduceProtocolState(base,delta(3,[{op:'set',path:['tracks',0,'level'],value:.8},{op:'delete',path:['old']} ]));assert.equal(base.data.tracks[0].level,.5);assert.deepEqual(next.data,{tracks:[{level:.8}]});});
test('revision gap requests resync instead of applying divergent delta',()=>{const base=reduceProtocolState(initialProtocolState(),snapshot(10,{value:1}));const next=reduceProtocolState(base,delta(12,[{op:'set',path:['value'],value:2}]));assert.equal(next.data.value,1);assert.equal(next.status,'resyncing');assert.deepEqual(resyncRequest(next),{v:1,type:'resync',from_rev:10,reason:{expected:11,received:12}});});
test('heartbeat updates connection health without changing revision',()=>{const base=reduceProtocolState(initialProtocolState(),snapshot(1,{}));const next=reduceProtocolState(base,{v:1,type:'heartbeat'},123);assert.equal(next.revision,1);assert.equal(next.lastHeartbeatAt,123);});
test('command tracker correlates ack and reject by id',()=>{const tracker=new CommandTracker();const command=tracker.create({target:'transport',action:'start'},10);const settled=tracker.settle({v:1,type:'ack',id:command.id,rev:4});assert.equal(settled.status,'ack');assert.equal(settled.revision,4);assert.equal(tracker.pending.size,0);});
test('sustained slider movement stays bounded and preserves final value',()=>{const queue=new OutboundQueue();for(let i=0;i<1000;i++)queue.enqueue({v:1,type:'command',id:`move-${i}`,command:{value:i}},{delivery:'coalescible',key:'cutoff'});queue.enqueue({v:1,type:'command',id:'final',command:{value:1000}},{delivery:'coalescible',key:'cutoff',final:true});assert.equal(queue.size,1);assert.deepEqual(queue.drain(),[{v:1,type:'command',id:'final',command:{value:1000},final:true}]);});
test('reliable queue never silently drops commands',()=>{const queue=new OutboundQueue({reliableLimit:1});queue.enqueue({v:1,type:'command',id:'a',command:{}});assert.throws(()=>queue.enqueue({v:1,type:'command',id:'b',command:{}}),ProtocolError);});
