import test from 'node:test';
import assert from 'node:assert/strict';
import {RealtimeSession,stableClientId} from '../web/realtime-session.js';
if(!globalThis.CustomEvent){globalThis.CustomEvent=class CustomEvent extends Event{constructor(type,init={}){super(type);this.detail=init.detail;}};}
class FakeSocket extends EventTarget{constructor(){super();this.readyState=0;this.sent=[];this.closed=false;}open(){this.readyState=1;this.dispatchEvent(new Event('open'));}receive(message){this.dispatchEvent(new MessageEvent('message',{data:JSON.stringify(message)}));}send(message){this.sent.push(JSON.parse(message));}close(){this.closed=true;this.readyState=3;this.dispatchEvent(new Event('close'));}}
function harness(options={}){const sockets=[],timers=[];const session=new RealtimeSession({socketFactory:()=>{const socket=new FakeSocket();sockets.push(socket);return socket;},url:'ws://device',channels:['params','transport'],clientId:'browser-test-session',setTimer:(fn,delay)=>{const timer={fn,delay,cancelled:false};timers.push(timer);return timer;},clearTimer:timer=>{timer.cancelled=true;},...options});return{session,sockets,timers};}
test('open negotiates hello and subscription before queued commands',()=>{const{session,sockets}=harness();session.connect();const id=session.command({target:'transport',action:'start'});sockets[0].open();assert.deepEqual(sockets[0].sent.map(x=>x.type),['hello','subscribe','command']);assert.equal(sockets[0].sent[0].client_id,'browser-test-session');assert.ok(sockets[0].sent[1].channels.includes('ownership'));assert.equal(sockets[0].sent[2].id,id);});
test('hello capabilities are exposed without mutating protocol state',()=>{const{session,sockets}=harness();const hellos=[];session.addEventListener('hello',event=>hellos.push(event.detail));session.connect();sockets[0].open();sockets[0].receive({v:1,type:'hello',server:'ingenue',capabilities:{channels:['grid'],commands:['grid.key']}});assert.equal(hellos.length,1);assert.equal(hellos[0].capabilities.commands[0],'grid.key');assert.equal(session.state.status,'subscribing');});
test('snapshot and ordered delta become authoritative session state',()=>{const{session,sockets}=harness();session.connect();sockets[0].open();sockets[0].receive({v:1,type:'snapshot',rev:4,state:{transport:{playing:false}}});sockets[0].receive({v:1,type:'delta',rev:5,operations:[{op:'set',path:['transport','playing'],value:true}]});assert.equal(session.state.status,'synced');assert.equal(session.state.revision,5);assert.equal(session.state.data.transport.playing,true);});
test('revision gap sends one explicit resync request and preserves state',()=>{const{session,sockets}=harness();session.connect();sockets[0].open();sockets[0].receive({v:1,type:'snapshot',rev:2,state:{value:10}});sockets[0].receive({v:1,type:'delta',rev:4,operations:[{op:'set',path:['value'],value:20}]});assert.equal(session.state.data.value,10);assert.equal(session.state.status,'resyncing');assert.equal(sockets[0].sent.filter(x=>x.type==='resync').length,1);});
test('ack exposes applied result and clears inflight',()=>{const{session,sockets}=harness();const results=[];session.addEventListener('command',e=>results.push(e.detail));session.connect();sockets[0].open();const id=session.command({target:'param',action:'describe'});assert.equal(session.inflight.has(id),true);sockets[0].receive({v:1,type:'ack',id,rev:9,result:{param:{id:'cutoff',normalized:.5}}});assert.equal(results[0].status,'ack');assert.equal(results[0].result.param.id,'cutoff');assert.equal(session.commands.pending.size,0);assert.equal(session.inflight.size,0);});
test('socket close marks only sent commands uncertain and leaves queued work',()=>{const{session,sockets}=harness();const results=[];session.addEventListener('command',e=>results.push(e.detail));session.connect();sockets[0].open();const sent=session.command({target:'transport',action:'start'});sockets[0].readyState=0;const queued=session.command({target:'transport',action:'stop'});sockets[0].readyState=1;sockets[0].close();assert.equal(results.find(x=>x.id===sent).status,'uncertain');assert.equal(results.find(x=>x.id===sent).result,null);assert.equal(session.commands.pending.has(sent),false);assert.equal(session.commands.pending.has(queued),true);assert.equal(session.queue.size,1);});
test('socket close schedules exponential reconnect and resubscribes with the same client id',()=>{const{session,sockets,timers}=harness({reconnect:{minMs:100,maxMs:1000,factor:2}});session.connect();sockets[0].open();sockets[0].close();const reconnect=timers.find(t=>t.delay===100&&!t.cancelled);assert.ok(reconnect);reconnect.fn();assert.equal(sockets.length,2);sockets[1].open();assert.deepEqual(sockets[1].sent.slice(0,2).map(x=>x.type),['hello','subscribe']);assert.equal(sockets[1].sent[0].client_id,sockets[0].sent[0].client_id);});
test('heartbeat watchdog closes stale sockets',()=>{const{session,sockets,timers}=harness({heartbeatTimeoutMs:321});let stale=0;session.addEventListener('stale',()=>stale++);session.connect();sockets[0].open();const watchdog=timers.find(t=>t.delay===321&&!t.cancelled);assert.ok(watchdog);watchdog.fn();assert.equal(stale,1);assert.equal(sockets[0].closed,true);});
test('continuous commands remain coalesced and tracker stays bounded while disconnected',()=>{const{session,sockets}=harness();session.connect();for(let i=0;i<500;i++)session.command({target:'param',action:'set',args:{id:'cutoff',value:i}},{delivery:'coalescible',key:'cutoff'});assert.equal(session.queue.size,1);assert.equal(session.commands.pending.size,1);sockets[0].open();const commands=sockets[0].sent.filter(x=>x.type==='command');assert.equal(commands.length,1);assert.equal(commands[0].command.args.value,499);});
test('stable client id is reused from session storage',()=>{const values=new Map();const storage={getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,value)};const first=stableClientId({storage,randomUUID:()=> '11111111-2222-4333-8444-555555555555'});const second=stableClientId({storage,randomUUID:()=> 'aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee'});assert.equal(first,second);assert.match(first,/^browser-/);});
test('session ownership helpers emit control-plane commands and inspect snapshots',()=>{const{session,sockets}=harness();session.connect();sockets[0].open();const claim=session.claim('grid:1');const release=session.release('grid:1');const releaseAll=session.releaseAll();const commands=sockets[0].sent.filter(x=>x.type==='command');assert.deepEqual(commands.slice(-3).map(x=>x.command.action),['claim','release','release_all']);assert.deepEqual(commands.slice(-3).map(x=>x.id),[claim,release,releaseAll]);sockets[0].receive({v:1,type:'snapshot',rev:1,state:{ownership:{resources:{'grid:1':{client_id:'browser-test-session'}}}}});assert.equal(session.owns('grid:1'),true);});
test('default timers preserve the global receiver required by browsers',()=>{
  const originalSetTimeout=globalThis.setTimeout;
  const originalClearTimeout=globalThis.clearTimeout;
  const sockets=[];
  const timers=[];
  globalThis.setTimeout=function(fn,delay){assert.equal(this,globalThis);const timer={fn,delay,cancelled:false};timers.push(timer);return timer;};
  globalThis.clearTimeout=function(timer){assert.equal(this,globalThis);timer.cancelled=true;};
  try{
    const session=new RealtimeSession({socketFactory:()=>{const socket=new FakeSocket();sockets.push(socket);return socket;},url:'ws://device',clientId:'browser-default-timer'});
    session.connect();
    sockets[0].open();
    assert.equal(timers.length,1);
    assert.equal(timers[0].delay,5000);
    session.disconnect();
    assert.equal(timers[0].cancelled,true);
  }finally{
    globalThis.setTimeout=originalSetTimeout;
    globalThis.clearTimeout=originalClearTimeout;
  }
});
