import test from 'node:test';
import assert from 'node:assert/strict';
import {percentile,summarize,runPool,createHttpProbe,createWebSocketConnectProbe,createMatronRoundTripProbe,createOscControlRoundTripProbe,runTransportDiagnostics} from '../web/transport-diagnostics.js';

test('percentile and summarize are stable',()=>{assert.equal(percentile([1,2,3,4],.5),2);assert.deepEqual(summarize([4,1,NaN,3,2]),{count:4,min_ms:1,mean_ms:2.5,p50_ms:2,p95_ms:4,p99_ms:4,max_ms:4});});
test('runPool caps concurrency',async()=>{let active=0,max=0;const out=await runPool(8,3,async i=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,2));active--;if(i===5)throw new Error('boom');return i;});assert.equal(max,3);assert.equal(out.errors.length,1);assert.equal(out.values.length,7);});
test('http probe measures successful request',async()=>{let t=0;const probe=createHttpProbe({url:'/x',now:()=>t+=5,fetchImpl:async()=>({ok:true,status:200,text:async()=>''})});assert.equal(await probe(),5);});
class FakeWS{static instances=[];constructor(){this.handlers={};FakeWS.instances.push(this);queueMicrotask(()=>this.emit('open',{}));}addEventListener(n,fn){(this.handlers[n]??=[]).push(fn);}send(msg){this.sent=msg;}close(){}emit(n,e){for(const fn of this.handlers[n]||[])fn(e);}}
test('websocket connect probe measures open',async()=>{let t=0;const probe=createWebSocketConnectProbe({WebSocketImpl:FakeWS,url:'ws://x',now:()=>t+=4});assert.equal(await probe(),4);});
test('matron round-trip resolves only after matching token',async()=>{let t=0;class EchoWS extends FakeWS{send(msg){super.send(msg);queueMicrotask(()=>this.emit('message',{data:'noise'}));queueMicrotask(()=>this.emit('message',{data:'ACK fixed'}));}}const probe=createMatronRoundTripProbe({WebSocketImpl:EchoWS,url:'ws://x',now:()=>t+=7,tokenFactory:()=> 'fixed'});assert.equal(await probe(),7);});
test('OSC control probe waits for Lua acknowledgement after HTTP dispatch',async()=>{let t=0,request=null;class OscWS extends FakeWS{send(msg){super.send(msg);queueMicrotask(()=>this.emit('message',{data:'ING_OSC_PROBE_READY'}));}}const fetchImpl=async(url,options)=>{request={url,options};queueMicrotask(()=>OscWS.instances.at(-1).emit('message',{data:'unrelated'}));queueMicrotask(()=>OscWS.instances.at(-1).emit('message',{data:'fixed'}));return {ok:true,status:204};};const probe=createOscControlRoundTripProbe({WebSocketImpl:OscWS,fetchImpl,wsUrl:'ws://x',ctlUrl:'/api/ctl',now:()=>t+=11,tokenFactory:()=> 'fixed'});assert.equal(await probe(),11);assert.equal(request.url,'/api/ctl');assert.deepEqual(JSON.parse(request.options.body),{k:'param',id:'__ingenue_probe_fixed',v:1});});
test('report includes full OSC control round-trip',async()=>{const report=await runTransportDiagnostics({samples:10,concurrency:2,httpUrl:'x',ctlUrl:'ctl',wsUrl:'y',httpProbe:async()=>1,wsConnectProbe:async()=>2,matronProbe:async()=>3,oscControlProbe:async()=>4});assert.equal(report.benchmark_version,4);assert.equal(report.osc_control_roundtrip.latency.p50_ms,4);});
