import {RealtimeSession} from './realtime-session.js';
import {realtimeUrl} from './realtime-inspector.js';
import {PressLedger} from './performance-core.js';
import {
  BUILDER_TEMPLATES,BuilderError,BuilderStore,appendBuilderWidget,builderTemplate,createBuilderWidget,
  defaultBuilderSchema,parseBuilderSchema,schemaFromScriptMetadata,serializeBuilderSchema,updateBuilderLayout,
  writableParameterOptions,
} from './builder-core.js';
import {button,element,fileName,formattedParameter,option} from './builder-dom.js';
import {BuilderMidiRuntime} from './builder-midi-runtime.js';
import {createBuilderEditor} from './builder-editor-ui.js';
import {previewEncoder,previewKey,previewParam} from './builder-preview-native.js';
import {previewArc,previewGamepad,previewGrid,previewMidi,updateDeviceFrames} from './builder-preview-devices.js';

// Fixed typed contracts for static/security review:
// {target: 'control', action: 'key'} · {target: 'control', action: 'enc'}
// {target: 'param', action: 'set_normalized'} · node.textContent = widget.label

export function mountBuilderSurface(root=document,options={}){
  const locationLike=options.locationLike||globalThis.location,url=options.url||realtimeUrl(locationLike);
  const session=options.session||new RealtimeSession({socketFactory:value=>new WebSocket(value),url,channels:['device','script','params','control','grid','arc']});
  const store=options.store||new BuilderStore(options.storage||globalThis.localStorage),navigatorLike=options.navigatorLike||globalThis.navigator,globalLike=options.globalLike||globalThis,confirmLike=options.confirmLike||globalThis.confirm?.bind(globalThis)||(()=>true);
  const endpoint=element(root,'builder-endpoint'),status=element(root,'builder-status'),revision=element(root,'builder-revision'),scriptEl=element(root,'builder-script'),nameInput=element(root,'builder-name'),columnsSelect=element(root,'builder-columns'),editor=element(root,'builder-editor'),count=element(root,'builder-count'),preview=element(root,'builder-preview'),previewName=element(root,'builder-preview-name'),notice=element(root,'builder-notice'),jsonArea=element(root,'builder-json'),paramOptions=element(root,'builder-param-options'),exportButton=element(root,'builder-export'),copyButton=element(root,'builder-copy'),downloadButton=element(root,'builder-download'),importButton=element(root,'builder-import'),resetButton=element(root,'builder-reset'),templateSelect=element(root,'builder-template'),templateApply=element(root,'builder-template-apply'),presetName=element(root,'builder-preset-name'),presetSelect=element(root,'builder-preset'),presetSave=element(root,'builder-preset-save'),presetLoad=element(root,'builder-preset-load'),presetDelete=element(root,'builder-preset-delete'),midiEnable=element(root,'builder-midi-enable'),midiStatus=element(root,'builder-midi-status');
  endpoint.textContent=url;

  let activeScript=null,schema=null,ready=false,stateData=null,catalogGeneration=null,catalogRequestedFor=null,metadataRevision=null,parameterDescriptors=new Map();
  let keyLedger=makeLedger('control','key',target=>({n:target.n})),gridLedger=makeLedger('grid','key',target=>target),arcLedger=makeLedger('arc','key',target=>target);
  const paramLanes=new Map(),settlements=new Map();
  const midiRuntime=new BuilderMidiRuntime({navigatorLike,onStatus:value=>{midiStatus.textContent=value;},command:message=>{if(ready)session.command(message);}});
  function makeLedger(target,action,args){return new PressLedger((value,z)=>{if(ready)session.command({target,action,args:{...args(value),z}});});}
  const isReady=()=>ready,getStateData=()=>stateData,getDescriptors=()=>parameterDescriptors;

  function setNotice(message,error=false){notice.textContent=message||'';notice.dataset.error=error?'true':'false';}
  function setEditorEnabled(enabled){root.querySelectorAll('[data-builder-action]').forEach(control=>{if('disabled'in control)control.disabled=!enabled;});nameInput.disabled=!enabled;columnsSelect.disabled=!enabled;jsonArea.disabled=!enabled;}
  function setPreviewEnabled(enabled){ready=enabled;root.body?.toggleAttribute('data-builder-ready',enabled);preview.querySelectorAll('button,input,select').forEach(control=>{control.disabled=!enabled;});}
  function nextWidgetId(){const token=globalThis.crypto?.randomUUID?.()||`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;return `w-${token}`.slice(0,64);}
  function persist(next,message='Surface saved for this script.'){schema=store.save({...next,metadata:{source:'local',revision:null}});renderAll();setNotice(message);return schema;}
  function mutate(operation,message){if(!schema||!activeScript)return;try{persist(operation(schema),message);}catch(error){setNotice(`Builder change rejected: ${error.message}`,true);}}
  const renderEditor=createBuilderEditor({editor,count,getSchema:()=>schema,mutate});

  function updatePresetButtons(){presetLoad.disabled=!presetSelect.value;presetDelete.disabled=!presetSelect.value;}
  function refreshPresetOptions(){const selected=presetSelect.value;presetSelect.replaceChildren(option('','select preset'));if(activeScript)for(const name of store.listPresets(activeScript))presetSelect.append(option(name));if([...presetSelect.options].some(item=>item.value===selected))presetSelect.value=selected;updatePresetButtons();}
  function applyMetadata(raw){const metadata=schemaFromScriptMetadata(raw,activeScript);if(!metadata||store.loadInfo(activeScript).exists)return false;schema=metadata;metadataRevision=metadata.metadata.revision||'script';renderAll();setNotice('Loaded the script-provided Ingenue surface. Save any edit to create a local override.');return true;}
  function loadScript(script,scriptState=null){releaseEverything();paramLanes.clear();settlements.clear();activeScript=script;catalogGeneration=null;catalogRequestedFor=null;metadataRevision=null;parameterDescriptors=new Map();if(!script){schema=null;renderAll();setNotice('Start a script to create or use its control surface.');return;}try{const info=store.loadInfo(script);schema=info.schema;setNotice(info.migrated?'Migrated the stored v1 surface to schema v2.':info.exists?'Loaded the local surface for this exact script.':'No local surface yet. Choose a template or add widgets.');}catch(error){schema=defaultBuilderSchema(script);setNotice(`Stored surface was ignored: ${error.message}.`,true);}if(!store.has(script))applyMetadata(scriptState);renderAll();}

  function renderPreview(){
    releaseEverything();keyLedger=makeLedger('control','key',target=>({n:target.n}));gridLedger=makeLedger('grid','key',target=>target);arcLedger=makeLedger('arc','key',target=>target);paramLanes.clear();settlements.clear();preview.replaceChildren();
    if(!schema){previewName.textContent='Surface';preview.style.setProperty('--builder-columns','1');return;}
    previewName.textContent=schema.name;preview.style.setProperty('--builder-columns',String(schema.columns));const fragment=document.createDocumentFragment();
    const common={root,session,isReady,stateData:getStateData,parameterDescriptors:getDescriptors,paramLanes,settlements,keyLedger,gridLedger,arcLedger,makeLedger};
    for(const widget of schema.widgets){let node;if(widget.type==='key')node=previewKey(widget,common);else if(widget.type==='encoder')node=previewEncoder(widget,common);else if(widget.type==='param')node=previewParam(widget,common);else if(widget.type==='grid')node=previewGrid(widget,common);else if(widget.type==='arc')node=previewArc(widget,common);else if(widget.type==='midi')node=previewMidi(widget);else if(widget.type==='gamepad')node=previewGamepad(widget,common);else{node=document.createElement('article');node.className=widget.type==='label'?'preview-widget preview-label':'preview-widget';node.dataset.type=widget.type;if(widget.type==='label')node.textContent=widget.label;}node.style.setProperty('--widget-span',String(widget.span));fragment.append(node);}
    preview.append(fragment);midiRuntime.setWidgets(schema.widgets);setPreviewEnabled(ready);
  }
  function renderParameterOptions(){paramOptions.replaceChildren();for(const descriptor of parameterDescriptors.values()){const item=option(descriptor.id,descriptor.name);item.label=descriptor.name;paramOptions.append(item);}}
  function renderAll(){setEditorEnabled(Boolean(schema&&activeScript));if(schema){nameInput.value=schema.name;columnsSelect.value=String(schema.columns);jsonArea.value=serializeBuilderSchema(schema);}else{nameInput.value='';columnsSelect.value='1';jsonArea.value='';}renderEditor();renderPreview();refreshPresetOptions();}
  function updateDescriptor(raw){if(!raw||typeof raw.id!=='string')return;const descriptor={...(parameterDescriptors.get(raw.id)||{}),...raw,normalized:Number(raw.normalized)};parameterDescriptors.set(raw.id,descriptor);for(const entry of paramLanes.values()){if(entry.widget.paramId!==raw.id||!Number.isFinite(descriptor.normalized))continue;entry.lane.lastApplied=descriptor.normalized;entry.range.value=String(descriptor.normalized);entry.output.textContent=formattedParameter(descriptor,descriptor.normalized);}}

  for(const template of BUILDER_TEMPLATES)templateSelect.append(option(template.id,template.name));
  root.querySelectorAll('[data-add-widget]').forEach(control=>control.addEventListener('click',()=>mutate(current=>appendBuilderWidget(current,createBuilderWidget(control.dataset.addWidget,nextWidgetId())),`${control.dataset.addWidget} widget added.`)));
  nameInput.addEventListener('change',()=>mutate(current=>updateBuilderLayout(current,{name:nameInput.value}),'Surface name updated.'));columnsSelect.addEventListener('change',()=>mutate(current=>updateBuilderLayout(current,{columns:Number(columnsSelect.value)}),'Surface columns updated.'));
  templateApply.addEventListener('click',()=>{if(!activeScript)return;if(schema?.widgets.length&&!confirmLike(`Replace the current surface with the ${templateSelect.selectedOptions[0]?.textContent} template?`))return;persist(builderTemplate(activeScript,templateSelect.value),'Template applied and saved as a local surface.');});
  presetSave.addEventListener('click',()=>{if(!schema)return;try{const name=store.savePreset(presetName.value,schema);presetName.value='';refreshPresetOptions();presetSelect.value=name;updatePresetButtons();setNotice(`Preset ${name} saved.`);}catch(error){setNotice(`Preset rejected: ${error.message}`,true);}});
  presetLoad.addEventListener('click',()=>{if(!activeScript||!presetSelect.value)return;try{persist(store.loadPreset(activeScript,presetSelect.value),`Preset ${presetSelect.value} loaded.`);}catch(error){setNotice(error.message,true);}});
  presetDelete.addEventListener('click',()=>{if(!activeScript||!presetSelect.value)return;try{const name=presetSelect.value;if(confirmLike(`Delete preset ${name}?`)){store.removePreset(activeScript,name);refreshPresetOptions();setNotice(`Preset ${name} deleted.`);}}catch(error){setNotice(error.message,true);}});presetSelect.addEventListener('change',updatePresetButtons);
  midiEnable.addEventListener('click',async()=>{try{await midiRuntime.enable();setNotice('Browser MIDI is active for MIDI widgets.');}catch(error){setNotice(error.message,true);}});
  exportButton.addEventListener('click',()=>{if(schema){jsonArea.value=serializeBuilderSchema(schema);setNotice('Current schema exported below.');}});
  copyButton.addEventListener('click',async()=>{if(!schema)return;const serialized=serializeBuilderSchema(schema);jsonArea.value=serialized;try{if(typeof navigatorLike.clipboard?.writeText!=='function')throw new Error('clipboard unavailable');await navigatorLike.clipboard.writeText(serialized);setNotice('Schema copied to the clipboard.');}catch{setNotice('Clipboard unavailable. Copy the JSON field manually.',true);}});
  downloadButton.addEventListener('click',()=>{if(!schema)return;const blob=new Blob([serializeBuilderSchema(schema)],{type:'application/json'}),objectUrl=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=objectUrl;anchor.download=fileName(schema.script);anchor.hidden=true;root.body?.append(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(objectUrl);setNotice('Schema download prepared.');});
  importButton.addEventListener('click',()=>{if(!activeScript)return;try{persist({...parseBuilderSchema(jsonArea.value,activeScript),metadata:{source:'import',revision:null}},'Schema imported and saved for the active script.');}catch(error){setNotice(`Import rejected: ${error.message}`,true);}});
  resetButton.addEventListener('click',()=>{if(!activeScript||!confirmLike(`Reset the UI surface for ${activeScript}?`))return;schema=store.remove(activeScript);renderAll();setNotice('Local surface removed. Script metadata or an empty layout is active.');if(stateData?.script)applyMetadata(stateData.script);});

  session.addEventListener('state',event=>{const state=event.detail;stateData=state.data;status.textContent=state.status;revision.textContent=state.revision??'—';const nextScript=state.data?.script?.active?state.data.script.name:null;scriptEl.textContent=nextScript||'no active script';if(nextScript!==activeScript){ready=false;loadScript(nextScript,state.data?.script);}else if(nextScript&&!store.has(nextScript)){const token=state.data?.script?.ingenue_ui?.metadata?.revision??state.data?.script?.ui_surface?.metadata?.revision??null;if(token!==metadataRevision&&applyMetadata(state.data?.script))metadataRevision=token;}const wasReady=ready,nextReady=state.status==='synced'&&Boolean(nextScript);if(!nextReady&&wasReady)releaseEverything();setPreviewEnabled(nextReady);const rawCatalog=state.data?.params;if(rawCatalog&&rawCatalog.generation!==catalogGeneration){catalogGeneration=rawCatalog.generation;parameterDescriptors=new Map(writableParameterOptions(rawCatalog).map(item=>[item.id,{...item,...rawCatalog.items.find(raw=>raw?.id===item.id)}]));renderParameterOptions();renderPreview();}if(nextScript&&rawCatalog?.generation==='none'&&catalogRequestedFor!==nextScript){catalogRequestedFor=nextScript;session.command({target:'param',action:'catalog',args:{}});setNotice('Requesting the active script parameter catalog…');}if(state.status==='reconnecting')setNotice('Connection lost. Held controls and MIDI gates were released; the editor remains available.');else if(nextReady&&schema)updateDeviceFrames({root:preview,schema,stateData:getStateData});});
  session.addEventListener('command',event=>{const detail=event.detail,lane=settlements.get(detail.id);if(lane){settlements.delete(detail.id);const next=lane.settle(detail.id,detail.status);if(next)settlements.set(next,lane);if(detail.status==='reject')for(const entry of paramLanes.values())if(entry.lane===lane&&Number.isFinite(lane.lastApplied)){entry.range.value=String(lane.lastApplied);entry.output.textContent=lane.lastApplied.toFixed(3);}}if(detail.result?.param)updateDescriptor(detail.result.param);if(detail.status==='reject'||detail.status==='uncertain')setNotice(detail.failure?.message||detail.error||`Builder command ${detail.status}`,true);});
  session.addEventListener('protocolerror',event=>setNotice(`Protocol error: ${event.detail.message}`,true));

  function releaseEverything(){keyLedger.releaseAll();gridLedger.releaseAll();arcLedger.releaseAll();midiRuntime.releaseAll();preview.querySelectorAll('.preview-grid,.preview-gamepad').forEach(node=>node._release?.());preview.querySelectorAll('[data-pressed=true]').forEach(node=>{node.dataset.pressed='false';});}
  globalLike.addEventListener?.('blur',releaseEverything);globalLike.addEventListener?.('pagehide',releaseEverything);root.addEventListener?.('visibilitychange',()=>{if(root.visibilityState==='hidden')releaseEverything();});
  setEditorEnabled(false);setPreviewEnabled(false);renderAll();session.connect();return{session,store,midiRuntime,get schema(){return schema;},destroy(){releaseEverything();midiRuntime.destroy();session.disconnect();}};
}
